name: Deploy Hugo
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.80.0'
          extended: true

      - name: Build Hugo
        run: hugo

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build Algolia Index
        run: |
          npm install
          ALGOLIA_APP_ID=${{ secrets.ALGOLIA_APP_ID }} ALGOLIA_ADMIN_KEY=${{ secrets.ALGOLIA_ADMIN_KEY }} ALGOLIA_INDEX_NAME=wuwenze.com ALGOLIA_INDEX_FILE=public/algolia.json npm run algolia

      - name: Setup OSSUTIL
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          # ALIYUN_OSS_ENDPOINT = oss-cn-hongkong.aliyuncs.com
          endpoint: "${{ secrets.ALIYUN_OSS_ENDPOINT }}"
          access-key-id: "${{ secrets.ALIYUN_OSS_ACCESS_KEY_ID }}"
          access-key-secret: "${{ secrets.ALIYUN_OSS_ACCESS_KEY_SECRET }}"

      - name: Deploy Aliyun OSS
        # ALIYUN_OSS_BUCKET_PATH = oss://wenzewoo/
        run: ossutil cp -r public ${{ secrets.ALIYUN_OSS_BUCKET_PATH }} --snapshot-path=.oss_history --update
